function showToast(message : string, icon : string = 'none', duration : number = 1800) {
  if (icon === 'success') {
    uni.showToast({
      title: message,
      icon: 'success',
      duration
    })
    return
  }
  uni.showToast({
    title: message,
    icon: 'none',
    duration
  })
}

export function showSuccess(message : string, duration : number = 1800) {
  showToast(message, 'success', duration)
}

export function showInfo(message : string, duration : number = 1800) {
  showToast(message, 'none', duration)
}

export function showError(message : string, duration : number = 1800) {
  showToast(message, 'none', duration)
}
