import { get, post } from './request'

export function submitFeedback(data : UTSJSONObject) : Promise<UTSJSONObject> {
  return post('/feedback/submit', data)
}

export function getFeedbackStats(sessionId : string) : Promise<UTSJSONObject> {
  return get('/feedback/stats', { sessionId })
}

export function getFeedbackList(sessionId : string, params : UTSJSONObject = {} as UTSJSONObject) : Promise<UTSJSONObject> {
  return get('/feedback/list', { sessionId, ...params })
}
