import { get, post, put, del } from './request'

export function getPlanList(params : UTSJSONObject = {} as UTSJSONObject) : Promise<UTSJSONObject> {
  return get('/plan/list', params)
}

export function getPlanDetail(planId : string) : Promise<UTSJSONObject> {
  return get(`/plan/detail/${planId}`)
}

export function createPlan(data : UTSJSONObject) : Promise<UTSJSONObject> {
  return post('/plan/create', data)
}

export function updatePlan(planId : string, data : UTSJSONObject) : Promise<UTSJSONObject> {
  return put(`/plan/update/${planId}`, data)
}

export function deletePlan(planId : string) : Promise<UTSJSONObject> {
  return del(`/plan/delete/${planId}`)
}

export function confirmPlan(planId : string) : Promise<UTSJSONObject> {
  return post(`/plan/confirm/${planId}`)
}

export function savePlanAsTemplate(planId : string) : Promise<UTSJSONObject> {
  return post(`/plan/save-template/${planId}`, {} as UTSJSONObject, { showLoading: true, loadingText: '正在保存模板...' })
}
